### ISSUE TITLE
Some minor details that change since last update

### ISSUE THREAD

**Issue by PsySc0rpi0n** [FleksySDK/fleksy#24]
I'm using Fleksy 11.0.0 in Android 8.0.0 in a Samsung Galaxy 7 Edge.

From last update I notice that after we insert a period in text messages, the app is not starting the next character as capital character and also it is not eliminating the extra space it usually adds after autocompleting a word. For the question mark, the extra space is eliminated and the next char is capital. Exclamation mark also works fine. Only the period is broken!

**Comment by theimpulson** [comment]
Hello @PsySc0rpi0n, it seems the issue you are raising is related to our public apps available on the Play Store. I am passing your feedback on to our development team, which is responsible for public apps. As this repository is for our SDK releases (not related to public apps), I am closing this issue.

**Comment by PsySc0rpi0n** [comment]
Thank you @theimpulson ...
Where can I check the development of this issue for the public app?

**Comment by Komigithob1981** [comment]
> I'm using Fleksy 11.0.0 in Android 8.0.0 in a Samsung Galaxy 7 Edge.
> 
> From last update I notice that after we insert a period in text messages, the app is not starting the next character as capital character and also it is not eliminating the extra space it usually adds after autocompleting a word. For the question mark, the extra space is eliminated and the next char is capital. Exclamation mark also works fine. Only the period is broken!

hi mi friend
