### ISSUE TITLE
How to use PanelView inside Fleksy keyboard

### ISSUE THREAD

**Issue by androidev1** [FleksySDK/fleksy#29]
I need to add some custom view as header and footer in keyboard view. Please help us how we can use the same.

**Comment by xevifar** [comment]
Hi @androidev1 , 
you can add the header as part of the [Frame View](https://docs.fleksy.com/sdk-android/api-reference-android/panelhelper/) adjusting the height to your needs. 
For the footer, maybe a button access would enable some behaviour to show up a custom bar on top of the keyboard ?

**Comment by androidev1** [comment]
Thanks for response.
I am not able to use PanelHelper class. where i should show showFrame or showFullFrame.
will we use this method inside  KeyboardService class or somewhere else.
Please help

**Comment by xevifar** [comment]
Hi @androidev1 , 
PanelHelper is part of our API interface, so you should be able to access and call it. You could call it as a normal class, inside your own integration. 
Have you been able to download our demo project from [here](https://github.com/FleksySDK/fleksy/tree/main/keyboardsdk-integrations/keyboard-android)  ? 
If so, from this [sample class](https://github.com/FleksySDK/fleksy/blob/main/keyboardsdk-integrations/keyboard-android/app/src/main/java/co/thingthing/sample/sdksample/SampleKeyboardService.kt) call PanelHelper as any other class.

**Comment by androidev1** [comment]
hi @xevifar 
Thanks for your solution. It worked for me perfectly.

I am getting strange issue that on first launch keyboard is not visible.

Steps to reproduce-
1. Turn on Fleksy keyboard from list
2. Select current keyboard Fleksy
3. Now, start typing, it would be blank on first launch.
4. If you change keyboard to old one and again choose fleksy keyboard then it is working fine.

I am using this version 'co.thingthing.fleksycore:fleksycore-release:4.0.1'

Please let me know if i am missing something.

**Comment by xevifar** [comment]
Hi @androidev1 , 
Glad to read that it worked out the proposed solution. 

It should work without problem the first launch. I've checked the demo project and it works at the first launch.
Could you check if there is something missing from the [demo project ](https://github.com/FleksySDK/fleksy/tree/main/keyboardsdk-integrations/keyboard-android)?

**Comment by androidev1** [comment]
In sample it works fine but when i use this with PanelHelper then it is creating issue in release build. It works fine in debug build

**Comment by xevifar** [comment]
Okay. Could you share the logs from the console and part of the source code of the _service_ ? Then we will try to reproduce internally. Thanks!

**Comment by androidev1** [comment]
I found the issue. I was missing resourceArchive-en-US.jet file in assets folder. 
Thanks for your support.
